### ISSUE TITLE
The npm plugin is currently incompatible with dispatch call of pulpcore >= 3.15

### ISSUE THREAD

**Issue by fao89** [pulp/pulp_npm#131]
Author: @mdellweg (mdellweg)

Redmine Issue: 9533, https://pulp.plan.io/issues/9533

---

None

**Comment by gpavinteractiv** [comment]
I currently can not install pulp-npm with ansible,

- If i try to install it concurrently with pulp-rpm, there is a pulpcore version requirement mutual exclusion from both pugins
- It I try to install it alone, pulp_installer fails a bit further by complaining about other modules still requiring pulpcore ~=3.20

Is there a workaround ?

**Comment by mdellweg** [comment]
Some version churn was expected around pulpcore 3.20. Please follow this thread to see the plugins landing with 3.20 compatibility releases: https://discourse.pulpproject.org/t/pulpore-3-20-planned-for-june-21st/465

The issue described in this issue however is fixed by 15637f6b. The bugtracking got confused by moving the issue, it seems.

**Comment by gpavinteractiv** [comment]
Thank you, I tried this but the playbook still fails at : 
```
TASK [pulp.pulp_installer.pulp_common : Run pip-compile to check pulpcore/plugin compatibility] ********************************************************************************************************************************
task path: /home/ansible/.ansible/collections/ansible_collections/pulp/pulp_installer/roles/pulp_common/tasks/preflight_function.yml:36
        "There are incompatible versions in the resolved dependencies:",
        "  pulpcore~=3.20.0 (from -r requirements.in (line 1))",
        "  pulpcore<3.22,>=3.16.0 (from pulp-rpm==3.17.6->-r requirements.in (line 3))",
        "  pulpcore<3.13,>=3.11 (from pulp-npm==0.1.0a3->-r requirements.in (line 2))"
````
I managed to work around this by ignore_error that task and manually install the .whl of the new plup-npm release.
